# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"say_hello": "00_core.ipynb",
         "HelloSayer": "00_core.ipynb",
         "say_hello2": "01_other.ipynb"}

modules = ["core.py",
           "other.py"]

doc_url = "https://rdarrylr.github.io/hellonbdev/"

git_url = "https://github.com/rdarrylr/hellonbdev/tree/master/"

def custom_doc_links(name): return None
