# AUTOGENERATED! DO NOT EDIT! File to edit: 00_core.ipynb (unless otherwise specified).

__all__ = ['say_hello', 'HelloSayer']

# Cell
def say_hello(to):
    "say hello to somebody"
    return f'Hello {to}!'

# Cell
class HelloSayer:
    "say hello to `to` using `say_hello`"
    def __init__(self, to): self.to = to
    def say(self): return say_hello(self.to)
    def yo(self): return say_hello('Yo')